ansible_become_pass: 1
#rolechecklist
d_hostname: tungsv
cd_hostname: true
tkusers: ["admin", "quantri"]
tkpass: "t1"
packages:
  - neofetch
  - tree
  - figlet
  - net-tools
skip_nexus_repo: true
nexusrepo: "deb http://192.168.1.10/ubuntu/ focal main restricted universe multiverse"
#LVM các biến tương ứng phải được chỉnh sửa cho phù hợp với số disk được tạo bởi terraform
volumes:
  - vg_name: vg1
    pvs: "/dev/sdb"
    lv_name: lv1
    mount_point: /app1
  - vg_name: vg2
    pvs: "/dev/sdc"
    lv_name: lv2
    mount_point: /app2
#network
skip_network_config: true
con_proxy: false
delete_proxy: true
network_cards:
  - intname: ens36
    ip_address: 192.168.41.154
    gateway: 192.168.41.2
    dns_servers:
      - 8.8.8.8
      - 1.1.1.1
  - intname: ens37
    ip_address: 192.168.42.155
    gateway: 192.168.42.2
    dns_servers:
      - 8.8.4.4
      - 1.0.0.1
http_proxy: "http://192.168.10.11:3128"
https_proxy: "http://192.168.10.11:3128"
ftp_proxy: "http://192.168.10.11:3128"
no_proxy: "192.168.*.*"
#ELKs
logstash_host: 192.168.41.152
logstash_port: 5044
