Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  
### ac1 vm  ####
  config.vm.define "ac1" do |ac1|
    ac1.vm.box_download_insecure = true
    ac1.disksize.size = 20000
    #eurolinux-vagrant/centos-stream-9
    ac1.vm.box = "ubuntu/jammy64"
    ac1.vm.hostname = "VCBSADMIN"
    ac1.vm.network "private_network", ip: "192.168.56.10"
    ac1.vm.provider "virtualbox" do |vb|
     vb.name = "ac1" 
     vb.cpus = 2
     vb.memory = 2024
    end
  end
end

