- name: Import Elasticsearch GPG key
  ansible.builtin.apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elasticsearch APT repository
  ansible.builtin.apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
    state: present

- name: Update all packages
  shell: apt-get update && apt-get upgrade -y

- name: Install packages
  ansible.builtin.apt:
    name:
      - openjdk-11-jdk-headless
      - elasticsearch
      - kibana
      - logstash
    state: present

- name: Copy configuration files
  ansible.builtin.copy:
    src: "templates/ELKm/{{ item }}"
    dest: "/etc/{{ item }}"
  with_items:
    - kibana/kibana.yml
    - logstash/conf.d/02-beats-input.conf
    - logstash/conf.d/30-elasticsearch-output.conf
    - logstash/conf.d/10-syslog-filter.conf

- name: Enable and start services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - elasticsearch
    - kibana
    - logstash