- name: Install Filebeat
  package:
    name: filebeat
    state: present

- name: Download Filebeat configuration file
  get_url:
    url: http://example.com/path/to/filebeat.yml
    dest: /etc/filebeat/filebeat.yml
    mode: 0644

- name: Enable and configure system module
  command: filebeat modules enable system

- name: Update Filebeat configuration
  lineinfile:
    path: /etc/filebeat/filebeat.yml
    regexp: '^output.elasticsearch:'
    line: 'output.elasticsearch: {hosts: ["<elasticsearch_host>:<elasticsearch_port>"]}'

- name: Start Filebeat service
  service:
    name: filebeat
    state: started
    enabled: yes