    - name: Copy and rename network configuration file
      loop: "{{ network_cards }}"
      template:
        src: netINT.yaml
        dest: "/etc/netplan/{{ item.intname }}.yaml"
      notify: apply netplan
      when: not skip_network_config


    - name: Configure proxy settings
      blockinfile:
        path: /etc/environment
        block: |
          http_proxy="{{ http_proxy }}"
          https_proxy="{{ https_proxy }}"
          ftp_proxy="{{ ftp_proxy }}"
          no_proxy="{{ no_proxy }}"
        state: present
      notify: not con_proxy

    - name: Delete proxy configuration
      lineinfile:
        path: /etc/environment
        state: absent
        regexp: 'http_proxy|https_proxy|ftp_proxy|no_proxy'
      notify: not delete_proxy
