#dung biến khai báo LVM trong thư mục để tạo ổ đĩa LVM 
#(lưu ý giữa số lượng ổ đĩa cứng add ở terraform và số lượng biến ở thư mục var )
- hosts: all
  become: yes
  tasks:
  - import_tasks: tasks/LVMtask.yml
